server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/talaba1}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
spring.security.user.password=admin123

jwt.secret=${JWT_SECRET:AFasfsafa#$%@$@ffgsgq353q53ESF3qr32R}
jwt.jwtExpirationInMs=8640000
jwt.jwtExpirationInMsRememberMe=604800000

system.root-directory=${FILES_DIR:files}

# Vergul bilan ajratilgan frontend manzillar
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200,https://talaba-frontend.pages.dev}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
